# Generated by Django 4.1.5 on 2023-02-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likedpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedPost',
            new_name='LikePost',
        ),
    ]
